#!/bin/bash

#
# Little Benchmark
# /doctor
# This script tries to fix the pew virtual environment
#

./scripts/bar-title 'LITTLE BENCHMARK DOCTOR' pwd

# Setup environment variables
export LB_VIRTUALENV_NAME='env'

# This is a pew variable and it controls where the virtual environment will be created.
export WORKON_HOME=$(pwd)

echo 'Trying to restore virtualenv named env...'
pew restore $LB_VIRTUALENV_NAME

echo 'Activating virtualenv named env...'
pew setproject $LB_VIRTUALENV_NAME .

# Unset environment variables
unset WORKON_HOME
unset LB_VIRTUALENV_NAME

# --- Finished
exit 0
