#!/bin/bash

#
# Little Benchmark
# /test
# This script handles running tests
#

# Show the fancy header
./scripts/bar-title 'LITTLE BENCHMARK TESTS' pwd

# Setup environment variables
export LB_VIRTUALENV_NAME='env'

# This is a pew variable and it controls where the virtual environment will be created.
export WORKON_HOME=$(pwd)

# echo 'Switching to env as virtualenv...'
# pew workon env

# Run tox for Python 2.7 only (for now)
# pew in $LB_VIRTUALENV_NAME tox -e py27

# Run tox will all environments (See tox.ini for more.)
pew in $LB_VIRTUALENV_NAME tox

# Unset environment variables
unset WORKON_HOME
unset LB_VIRTUALENV_NAME

# --- Finished
# exit 0
